encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "ency"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>", views.page, name="page"),
    path("search", views.search, name="search"),
    path("Rpage", views.Rpage, name="Rpage"),
    path("create", views.create, name="create"),
    path("edit/<str:entry>", views.edit, name="edit")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
import random
from . import util
from django.contrib import messages
import markdown2
from django.utils.safestring import mark_safe


def buscar(x):
	listSubEntry = []
	entries = util.list_entries()
	for entry in entries:		
		if x in entry:
			listSubEntry.append(entry)
	return listSubEntry

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def page(request, entry):
	if (util.get_entry(entry)!=None):
		return render(request, "encyclopedia/page.html", {
        "entry": entry.capitalize(),
        "content": markdown2.markdown(util.get_entry(entry))
        	})       	      
	else:
		return render(request, "encyclopedia/error.html")

def search(request):
	entry = request.GET.get('q')
	print(entry)	
	if(util.get_entry(entry)!=None):
		return render(request, "encyclopedia/page.html", {
        "entry": entry.capitalize(),
        "content": markdown2.markdown(util.get_entry(entry))
        	})
	else:
		lista = buscar(entry)
		return render(request, "encyclopedia/search.html", {
		"entry": entry,
        "result": lista
        	})

def Rpage(request):
	entries = util.list_entries()
	page = random.choice(entries)
	return render(request, "encyclopedia/page.html", {
        "entry": page.capitalize(),
        "content": markdown2.markdown(util.get_entry(page))
        	}) 

def create(request):
	entries = util.list_entries()
	if request.method == "POST":
		entry = request.POST["title"]
		content = request.POST["content"]	
		if entry in entries:
			messages.error(request, mark_safe("This entry already exists. <a href='/wiki/"+entry+"'>"+entry+" entry </a>"))
			return render(request, "encyclopedia/create.html",{
	   			"entry": entry,
	   		    "content": content
	   				})
		else:
			util.save_entry(entry, content)
			return render(request, "encyclopedia/page.html", {
        		"entry": entry.capitalize(),
        		"content": markdown2.markdown(util.get_entry(entry))
        			}) 
	else:
		return render(request, "encyclopedia/create.html")

def edit(request, entry):
	if request.method == "POST":
		text = request.POST["editable"]
		util.save_entry(entry, text)
		return render(request, "encyclopedia/page.html", {
        		"entry": entry.capitalize(),
        		"content": markdown2.markdown(util.get_entry(entry))
        			})
	else:
		return render(request, "encyclopedia/edit.html",{
			"entry": entry.capitalize(),
        	"txtedit": util.get_entry(entry)
				})

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create new page
{% endblock %}

{% block body %}
    <form action="{% url 'ency:create' %}" method="post">
    	{% csrf_token %}
    	<div class="form-group">
    		<label for="exampleFormControlInput1">Title</label>
    		<input id = "input"class="form-control" type="text" name="title" value="{{ entry }}">
    	</div>
    	<div class="form-group">
    		<label for="exampleFormControlTextarea1">Content</label>
    		<textarea name="content" class="form-control" id="exampleFormControlTextarea1" rows="3">{{ content }}</textarea>
  		</div>
  		<button type="submit" class="btn btn-primary">Create</button>
    </form>
    <div>
    {% for message in messages %}

                    <div class="alert alert-danger" role="alert">
                        <a class="close" href="#" data-dismiss="alert"></a>

                        {{ message }}

                    </div>
            {% endfor %}
    <div>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{entry}}
{% endblock %}

{% block body %}
	<form action="{% url 'ency:edit' entry %}" method="post">
    	{% csrf_token %}
    	<div class="form-group">
    		<label for="exampleFormControlInput1">Title</label>
    		<input id = "input"class="form-control" type="text" name="title" value="{{ entry }}" readonly>
    	</div>
 		<div class="form-group">
    		<label for="exampleFormControlTextarea1">Content</label>
    		<textarea name="editable" class="form-control" id="exampleFormControlTextarea1" rows="15">{{ txtedit }}</textarea>
  		</div>
 		<div>
 			<button type="submit" class="btn btn-success">Save changes</button>			
 		</div>
 	</form>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    <h1>The requested page was not found</h1>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <a href="{% url 'ency:page' entry %}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="rows">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'ency:search' %}" method="GET">
                    {% csrf_token %}
                    <input class="search" type="search" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'ency:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'ency:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'ency:Rpage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-10">
                {% block body %}
                {% endblock %}
            </div>
        </div>


    </body>
</html>

encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{entry}}
{% endblock %}

{% block body %}
    <div>
 	{{ content|safe }}
 	</div>
 	<div>
 		<a class="btn btn-success" href="{% url 'ency:edit' entry %}" role="button">Edit page</a>
 	</div>
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block body %}
    <h1>Related searches</h1>

    <ul>{% if not result %}
    		<li>Not results found.</li>
    	{% else %}	
        	{% for entry in result %}
           		<a href="{% url 'ency:page' entry %}"><li>{{ entry }}</li></a>
        	{% endfor %}
        {% endif %}
    </ul>

{% endblock %}